# Generated by Django 4.2.8 on 2024-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=75)),
                ("mensagem", models.TextField(blank=True)),
                ("data", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="contato",
            name="mensagem",
            field=models.TextField(blank=True),
        ),
    ]
